"""
NOTE:
This file is given to you to test your code.
DO NOT EDIT THIS FILE!
"""
from une_ai.assignments import SnakeGame
from snake_agent import SnakeAgent
from snake_agent_program import snake_agent_program

if __name__ == "__main__":
    snake_agent = SnakeAgent(snake_agent_program)
    snake_game = SnakeGame(snake_agent)

